[package]
name = "actix-test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-ws = "0.3.0"
env_logger = "0.11.5"
futures-util = { version = "0.3.31", features = ["sink"] }
log = "0.4.22"
serde = { version = "1.0", features = ["derive"] }
