[package]
name = "actix-test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-ws = "0.3.0"
futures-util = { version = "0.3.31", features = ["sink"] }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.40"
tracing-actix-web = "0.7.13"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
